BACKBONE: "resnet50"
HEAD_DIM: 1024
NHEADS: 3
EMBEDDING_DIM: 256
EMBEDDING_INTERMEDIATE: 1024
PROPOSAL_METHOD: "CONNECTED_COMPONENTS"
WARPED_SIZE: 250
EXPANSION_DELTA: 50
CLASSES: ["Abstract",
    "Body Text",
    "Equation label",
    "Equation",
    "Figure Caption",
    "Figure",
    "Other",
    "Page Footer",
    "Page Header",
    "Reference text",
    "Section Header",
    "Table Caption",
    "Table Note",
    "Table"]
TRAINING: True
